Feat/refunds
stranded-in-python/movix-billing-api pull request #19
Opened 2023-10-04 08:59 UTC by dogbusiness

2023-10-05 09:24 UTC, SBKubric requested changes
Есть пара проблем, а так готово к мерджу.

2023-10-05 09:24 UTC, SBKubric commented on .envs/.local/.billing
> +CLOUDPAYMENTS_TO_URL=https://api.cloudpayments.ru/payments
Название переменных вызывает вопросы.

Правильнее назвать CLOUDPAYMENTS_API

2023-10-05 09:24 UTC, SBKubric commented on .envs/.local/.billing
> +CLOUDPAYMENTS_OUR_URL=https://movix.sbkubric.com
Правильнее назвать HOST. Кстати, зачем она здесь?

2023-10-05 09:24 UTC, SBKubric commented on .envs/.local/.billing
> +CLOUDPAYMENTS_PUBLIC_ID=pk_0103f16b2a41849ad256055287c22
Это вообще треш. Эти данные (продовые, между прочим) не должны попадать в репу. Учитывая то, что репа сейчас публичная, особенно смешно. Данные инвалидировал.

2023-10-05 09:24 UTC, SBKubric commented on src/api/v1/payments_router.py
> +    token=Depends(read_internal_token),
нет авторизации пользователя

2023-10-05 09:35 UTC, dogbusiness commented
Правки учтены, за косяк с env извиняюсь

2023-10-08 19:37 UTC, closed without merging

2023-10-08 19:37 UTC, SBKubric commented
Смерджено в #22